name: CI

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop


jobs:
  tests:
    name: Unit tests
    # ubuntu-latest, ubuntu-18.04, or ubuntu-16.04
    # windows-latest, windows-2019, or windows-2016
    # macOS-latest or macOS-10.14
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
          java-version: 1.8
    - name: Maven package
      run: mvn -B package --file pom.xml
    
